### ISSUE TITLE
Milestone 3 Checklist

### ISSUE THREAD

**Issue by zchen156** [UBC-MDS/525-Group-5#10]
- [x] Setup your EMR cluster
- [x] Setup your EMR notebook
- [x] Develop a ML model using scikit-learn
- [x] Obtain best hyperparameter settings using spark's MLlib
