### ISSUE TITLE
Milestone 4 Checklist 

### ISSUE THREAD

**Issue by zchen156** [UBC-MDS/525-Group-5#11]
- [x] Use an EC2 instance. You can spin up a new EC2 instance.
- [x] Develop your API here in this notebook (Question 1).
- [x] Copy it to app.py file in EC2 instance (Question 2).
- [x] Run your API for other consumers and test it among your colleagues.
- [x] Summarize your journey.
