### ISSUE TITLE
Milestone 1

### ISSUE THREAD

**Issue by roanraina** [UBC-MDS/525-Group-5#2]
## Milestone 1 checklist  
- [ ] Team-work contract
- [ ] Creating a repository and project structure
     - [ ] init repo
     - [ ] `README`
     - [ ] `notebooks` folder
- [ ] Download Data
- [ ] Combining data CSVs
- [ ] Load the combined CSV to memory and perform a simple EDA
- [ ] Perform a simple EDA in R
- [ ] Compare run times on different machines
- [ ] Submit to Canvas

**Comment by roanraina** [comment]
`README` added in PR #1
