### ISSUE TITLE
Milestone 2 Checklist

### ISSUE THREAD

**Issue by zchen156** [UBC-MDS/525-Group-5#6]
- [x] Task 1: To set up a collaborative environment 
  - [x] Setup your EC2 instance with JupyterHub
  - [x] Install all necessary things needed in your UNIX server (Amazon EC2 instance)
  - [x] Set up your S3 bucket
  - [x] Move the data that you wrangled in your last milestone to S3
 
- [x] Task 2: Wrangle the data in preparation for machine learning
  - [x] Get the data from S3 in your notebook and make data ready for machine learning
